# Generated by Django 3.2.6 on 2021-08-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
