# Generated by Django 3.1.3 on 2021-09-29 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210923_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to=settings.AUTH_USER_MODEL), max_length=256),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default='Brasil', max_length=256),
        ),
        migrations.AddField(
            model_name='endereco',
            name='referencia',
            field=models.CharField(default='Casa de <django.db.models.fields.related.ForeignKey>', max_length=256),
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(choices=[('A', 'Apartamento'), ('R', 'Residência'), ('C', 'Comercial'), ('O', 'Outro')], default='O', max_length=1),
        ),
    ]
