# Generated by Django 3.2.6 on 2021-08-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=256)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagem', models.FileField(upload_to='media')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='categorias.categoria')),
                ('tags', models.ManyToManyField(related_name='produtos', to='categorias.Tag')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('visualizacoes', models.IntegerField()),
                ('vendas', models.IntegerField()),
            ],
        ),
    ]
