# Generated by Django 3.1.3 on 2021-10-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagem', models.FileField(upload_to='media')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('visualizacoes', models.IntegerField()),
                ('vendas', models.IntegerField()),
                ('is_disponivel', models.BooleanField(default=True)),
                ('estoque', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='categorias.categoria')),
                ('tags', models.ManyToManyField(related_name='produtos', to='categorias.Tag')),
            ],
        ),
    ]
