# Generated by Django 3.1.3 on 2021-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='foi_pago',
            field=models.BooleanField(default=False),
        ),
    ]
