# Generated by Django 3.1.3 on 2021-09-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
