# Generated by Django 3.1.3 on 2021-09-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_alter_carrinho_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
