# Generated by Django 3.1.3 on 2021-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210929_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='nome',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='referencia',
            field=models.CharField(default='', max_length=256),
        ),
    ]
