# Generated by Django 3.1.3 on 2021-10-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forma_pagamento', models.CharField(choices=[('P', 'Pix'), ('B', 'Boleto'), ('C', 'Crédito')], max_length=1)),
                ('quantidade_produtos', models.JSONField()),
                ('frete', models.DecimalField(decimal_places=2, max_digits=9)),
                ('endereco', models.ForeignKey(default='Excluído', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pedidos', to='accounts.endereco')),
                ('produtos', models.ManyToManyField(related_name='pedidos', to='produtos.Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
